# Generated by Django 5.0.1 on 2024-01-12 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospital', '0004_remove_hospital_departments_hospital_departments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('phone_number', models.CharField(max_length=10, unique=True)),
                ('disease', models.CharField(max_length=100)),
                ('appointed_doctor_name', models.CharField(max_length=100)),
                ('patient_status', models.CharField(choices=[('admitted', 'Admitted'), ('discharged', 'Discharged'), ('observation', 'In Observation')], max_length=50)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='VisitTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('activity', models.CharField(choices=[('IN', 'IN'), ('OUT', 'OUT')], max_length=3)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_tracks_patient', to='patient.patient')),
                ('patient_phone_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_tracks_phone_number', to='patient.patient', to_field='phone_number')),
            ],
        ),
    ]
