# Generated by Django 5.0.1 on 2024-01-09 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('disease', models.CharField(max_length=100)),
                ('appointed_doctor_name', models.CharField(max_length=100)),
                ('patient_status', models.CharField(choices=[('admitted', 'Admitted'), ('discharged', 'Discharged'), ('observation', 'In Observation')], max_length=50)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital')),
            ],
        ),
    ]
