# Generated by Django 4.2.8 on 2023-12-31 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospitalName', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=100)),
                ('disease', models.CharField(max_length=100)),
            ],
        ),
    ]
