# Generated by Django 5.0.1 on 2024-01-11 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='disease',
        ),
    ]
