# Generated by Django 5.0.1 on 2024-01-12 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_remove_hospital_disease'),
    ]

    operations = [
        migrations.CreateModel(
            name='Depratment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='department',
        ),
        migrations.AddField(
            model_name='hospital',
            name='departments',
            field=models.ManyToManyField(to='hospital.depratment'),
        ),
    ]
