# Generated by Django 5.0.1 on 2024-01-12 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_depratment_remove_hospital_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='departments',
        ),
        migrations.AddField(
            model_name='hospital',
            name='departments',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
